'use strict';

// file automatically generated by angular-template-cache

var templatesModule = require('angular')
	.module('templates', [])
	.run(['$templateCache', function($templateCache) {
		$templateCache.put('test-it/first.html', require('test-it/first.html'));

		$templateCache.put('test-it/second.html', require('test-it/second.html'));
	}
]);

module.exports = templatesModule;
