'use strict';

module.exports = {
	filesGlob: null,
	fileList: [],
	strict: true,
	style: 'browser',
	header: '// file automatically generated by angular-template-cache',
	moduleName: 'templates',
	newModule: true,
	keyPathPrefix: '',
	valuePathPrefix: '',
	quotmark: 'single',
	whitespace: 'tabs',
};
