'use strict';

module.exports = {
	filesGlob: null,
	fileList: [],
	strict: true,
	ignoreMissing: false,
	style: 'browser',
	header: '// file automatically generated by template-cache-builder',
	moduleName: 'templates',
	newModule: true,
	basePathPrefix: '',
	quotmark: 'single',
	whitespace: 'tabs'
};
